[package]
name = "amos-orchestrator"
version = "0.1.0"
edition = "2024"

[dependencies]
amos-common = { workspace = true }

anyhow = { workspace = true }
async-trait = "0.1"
base64 = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
config = { workspace = true }
ed25519-dalek = { version = "2.2.0", features = ["rand_core"] }
podman-api = { version = "0.11", default-features = false }
reqwest = { version = "0.13.3", features = ["json"] }
rsa = { version = "0.9.10", features = ["pem"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
tracing-journald = "0.3"
futures-util = "0.3.32"

[dev-dependencies]
serial_test = "3.4.0"
mockall = "0.14"
rand = "0.10.1"
tempfile = "3"
