[package]
name = "amos-api-mock-server"
version = "0.1.0"
edition = "2024"

[dependencies]
amos-common = { workspace = true }

axum = { version = "0.8.9", default-features = false, features = ["http1", "http2", "json", "tokio", "query"] }
serde_json = { workspace = true }
clap = { workspace = true }
config = { workspace = true }
env_logger = { workspace = true }
jsonwebtoken = { workspace = true }
log = { workspace = true }
# Ensure to match version with sea-orm-migration crate!
sea-orm = { version = "2.0.0-rc", features = ["sqlx-postgres", "sqlx-sqlite", "runtime-tokio-rustls", "macros", "with-json", "entity-registry"] }
sea-orm-migration = { version = "2.0.0-rc", features = ["sqlx-postgres", "runtime-tokio-rustls"] }
serde = { workspace = true }
tokio = { workspace = true }
tower-http = { version = "0.6", features = ["fs"] }

[dev-dependencies]
serial_test = "3.4.0"
tower = "0.5.3"
