[package]
name = "amos-api-mock-server"
version = "0.1.0"
edition = "2024"

[dependencies]
amos-common = { workspace = true }

axum = { version = "0.8.9", default-features = false, features = ["http1", "http2", "json", "tokio", "query"] }
chrono = { version = "0.4", features = ["serde"] }
serde_json = { workspace = true }
clap = { workspace = true }
config = { workspace = true }
env_logger = { workspace = true }
jsonwebtoken = { version = "10.4.0", features = ["rust_crypto"] }
log = { workspace = true }
sea-orm = { workspace = true }
sea-orm-timescale = { workspace = true }
# Ensure to match version with sea-orm from workspace!
sea-orm-migration = { version = "2.0.0-rc", features = ["sqlx-postgres", "runtime-tokio-rustls"] }
serde = { workspace = true }
tokio = { workspace = true }
tokio-stream = { version = "0.1", features = ["sync"] }
tower-http = { version = "0.6", features = ["fs"] }
uuid = { workspace = true }

[dev-dependencies]
serial_test = "3.4.0"
tower = "0.5.3"
