# Server Configuration
# Copy this file to config.toml and adjust values for your environment.
# All keys can also be set via environment variables prefixed APP_
# (e.g. APP_DATABASE_URL). Environment variables take precedence over this file.
# The path to this file can be chosen with the --config flag or, if that is
# not given, the APP_CONFIG_FILE environment variable.

# Connection string to the database for storing device information, groups etc.
# Env: APP_DATABASE_URL
database_url = "postgres://foo:bar@127.0.0.1/amos_db"

# Port that the API server will listen on
# Env: APP_HTTP_PORT
http_port = 8080

# This section configures the user authentication via JWTs
[jwt]

# Key for the subject inside a JWT
# Env: APP_JWT__SUBJECT_CLAIM
subject_claim = "sub"

# Key for the "display name" inside a JWT
# Env: APP_JWT__NAME_CLAIM
name_claim = "name"

# Public (RSA) key to verify the JWT's signature against
# Env: APP_JWT__PUBLIC_KEY
public_key = """-----BEGIN PUBLIC KEY-----
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAzP3Oc7fe4hRq7wMKxyfS
wiQclOzJIvoTLB0Tnxy6sEqUcg7WFV1Xcw25DuzIj6ZIlGhKIr6jKs+8G1rLymTZ
tIdJEx2wcKTPfTezth2/nMT9E2Dct0Q9aM2Yi/LUyVBmGD3Go14KoXA8EZbDOQOW
0wMREw5qsim6gI5Jm9O2XUUFwS+U28CoSqMKFNlJFdZodqa6mVsTQG6gmdtMbjyG
kX8KjEPcShNTZePWFimk3hBuBwSLtsYG2Ws2eyVYTbYPuI9Prmbfboykm/L9OYFZ
ZNyC/2bv7P9jJWIv6dwByKhcBZBHCxTYiPkTuxzN51JMyJA4okCPDoNJJRai5top
4oWtf7VQJHyKHUIpCZNMUD9bo+wBccvsd+o9WcQg/l5JRuKYipz61tiwKdbExPUh
RC6SgfDNg5YIPadLNbA+NGeFeXQtn+PYExcGkAcB/hbS6Ppj1Het67zuOGOZF8SE
/HzbIAQ4lHcOLCXVfGrXwB7DvhYYgQ3DAypvVS67fyggzcule2jcTGbrGpjb4YIk
eOovQuaa/ks1ymihNl18iJYZEDr/o/OhMiWaWOrLp/vnHeCIubgX6N1hMwopqgen
Anm8E788IHh9EybwO/uEiDqfSXlR8cmeBhD3B+vrkjbCnz/p6o8nhOzVabJUkYGa
RwsluOuHZzbXjtbwKS9rJ5sCAwEAAQ==
-----END PUBLIC KEY-----
"""

# This section configures audit logging of database changes
[audit]

# Which tables to create audit triggers on.
# If not set, all mutable tables are tracked.
# Env: APP_AUDIT__TRACKED_TABLES
# tracked_tables = ["devices", "tenants", "groups"]
