services:
  dev-container:
    image: mcr.microsoft.com/devcontainers/base:ubuntu-24.04
    volumes:
      - ../..:/workspaces:cached
      - podman-containers:/home/vscode/.local/share/containers
    privileged: true # Needed for podman
    command: sleep infinity

  mock-api-container:
    build: 
      context: ..
      dockerfile: .devcontainer/mock-api.Dockerfile
    restart: unless-stopped

volumes:
  podman-containers: