version: '3.8'

services:
  dev-container:
    image: mcr.microsoft.com/devcontainers/base:ubuntu-24.04
    volumes:
      - ../..:/workspaces:cached
      - podman_socket:/run/podman
    command: sleep infinity

  mock-api-container:
    build:
      context: ..
      dockerfile: .devcontainer/mock-api.Dockerfile
    environment:
      APP_DATABASE_URL: "sqlite::memory:"

  postgres-container:
    image: registry.access.redhat.com/hi/postgresql:18.3
    environment:
      POSTGRES_PASSWORD: dummy
    volumes:
      - "./10_setup_app_db.sh:/docker-entrypoint-initdb.d/10_setup_amos.sh:ro,Z"
      - "postgres_data:/var/lib/postgresql/data:rw"
  
  podman-container:
    image: quay.io/podman/stable:v5.8
    command: podman system service --time 0
    privileged: true
    volumes:
      - podman_socket:/run/podman


volumes:
  postgres_data:
  podman_socket:
