openapi: 3.2.0
info:
  title: AMOS Zero Downtime Linux Update - Device-facing API
  description: |-
    This is the device-facing part of the API, implemented in both server and orchestrator.
    Usually it is located inside the subpath ```/v1```. In order to gain access, devices 
    have to send a valid JWT token signed by their registered TPM as an ```Authorization: Bearer ...``` header
    (except for the /register endpoint).
  version: 2.0.0
externalDocs:
  description: The code is in our GitHub repository
  url: https://github.com/amosproj/amos2026ss01-zero-downtime-linux-updates
tags:
  - name: configuration
    description: Read information about the target state and report back to the server about the current one
  - name: logging
    description: Send logs to the server from various places
  - name: other
    description: Miscellaneous endpoints
paths:
  /device/os:
    get:
      tags:
        - configuration
      summary: Get the assigned OS version
      responses:
        '200':
          description: Successful retrieval of assignments
          content:
            application/json:
              schema:
                type: object
                required: 
                  - id
                  - commit_hash
                properties:
                  id:
                    type: integer
                  commit_hash: string
        '418':
          description: Device not registered
        '500':
          description: Server error
    put:
      tags:
        - configuration
      summary: Report the currently running OS version
      requestBody:
        description: "As found in ```amos_common::device_api::os```"
        content:
          application/json:
            schema:
              type: object
              properties:
                os_version_id:
                  type: integer
      responses:
        '201':
          description: Success
        '400':
          description: Bad request
        '418':
          description: Device not registered
        '500':
          description: Server error
  
  /device/apps:
    get:
      tags:
        - configuration
      summary: Get the assigned applications
      responses:
        '200':
          description: Successful retrieval of assignments
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  required: 
                    - id
                    - application_id
                    - image
                  properties:
                    id:
                      type: integer
                    application_id:
                      type: integer
                    image: string
                    config:
                      type: object
                      properties: 
                        environment:
                          type: object
        '418':
          description: Device not registered
        '500':
          description: Server error
    put:
      tags:
        - configuration
      summary: Report the currently running applications
      requestBody:
        description: "As found in ```amos_common::device_api::apps```"
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties: 
                  application_config_id:
                    type: integer
      responses:
        '201':
          description: Success
        '400':
          description: Bad request
        '418':
          description: Device not registered
        '500':
          description: Server error
  
  /device/logs:
    post:
      tags:
        - logging
      summary: Publish some log lines
      parameters: 
        - in: query
          name: application_id
          description: ID of the application producing these logs. Leave empty to signal these logs come from the OS.
          schema:
            type: integer
      requestBody: 
        description: "As found in ```amos_common::device_api::apps```"
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                required:
                  - level
                  - message
                properties: 
                  time:
                    type: string
                    description: ISO timestamp
                  level:
                    type: string
                    enum: [trace, debug, info, warn, error, fatal]
                  message: string
                  source: string
      responses:
        '201':
          description: Success
        '400':
          description: Bad request
        '418':
          description: Device not registered
        '500':
          description: Server error
  
  /device/ping:
    put:
      tags:
        - other
      summary: Send aliveness signal
      responses:
        '200':
          description: Success
        '418':
          description: Device not registered
        '500':
          description: Server error
  
  /register:
    post:
      tags:
        - other
      summary: Try and register a device with the server. Can only succeed if there is a pending registration.
      requestBody: 
        description: "As found in ```amos_common::device_api::register```"
        content: 
          application/json:
            schema: 
              type: object
              properties: 
                uuid: string
                serial_number: string
                endorsement_public_key: string
                signing_public_key: string
      responses:
        '201':
          description: Device registered successfully
        '400':
          description: Bad request
        '404':
          description: No pending registration found
        '500':
          description: Server error